<a href="https://colab.research.google.com/github/Data-Analysis-RCODI/ML-Playground/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I'm experimenting with the version 2 of Tensorflow here. 


In [0]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Data Types include float32, int32, string and others. We can put in value and data type. 


In [0]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

**Rank/Degree of Tensors**

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar. 

In [0]:
rank1_tensor = tf.Variable(["Test", "Ok", "Tim"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

To determine the rank of a tensor we can call the following method. I get numpy = 2, which means it is a rank 2 tensor. 

In [0]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of Tensors**

The shape of a tensor is simply the amount of elements that exist in each dimension. Tensorflow will try to determine the shape of a tensor but sometimes it can be unknown. 

In [0]:
rank2_tensor.shape

TensorShape([2, 2])

**Changing Shape**

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor. 


The example below shows how to change the shape of a tensor. 


In [0]:
tensor1 = tf.ones([1, 2, 3]) # tf.ones() create a shape [1, 2, 3] tensor full of ones 
print(tensor1)
tensor2 = tf.reshape(tensor1, [2, 3, 1])   # reshape existing data to shape [2, 3, 1]
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension 
#in that place, this will reshape the tensor to [3, 2]
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)



**Types of Tensor**

• Variable
• Constant 
• Placeholder

**Ways to Evaluate Tensor is to Create a Session**

We use the following default block of code




In [0]:
with tf. Session() as sess: # creates a session using the default graph
  tensor.eval()             # tensor will of course be the name of your tensor 